grid:
    method: 'bin gridding'

    dimensions  : [10, 200]
    #file        : 'foo'
    #spacing     : [0.1, 0.1]
    
shape:
    file: 'trajectory_data/polygons/Test SHP File.SHP'
    method: 'shapely contains'
    
    
surface:
    thickness:
        bins: 200
        coefficient: 0.002
    volume:
        bins: 20
        coefficient: 1.0
    
    gridded_products:
        hit_count                                   : 
#        hit_probability                             :
#        oil_volume                                  :
#        oil_volume_distribution                     :
#        min_time                                    :
#        max_of_uniform_oil_thickness                :
#        uniform_oil_thickness_distribution          :
#        distribution_of_max_uniform_oil_thickness   :
#            min_time    : False
#            run_stats   : True
        max_of_spillet_thickness                    :
        probability_of_standard_thickness           :
            standard_thicknesses:
                [0.0, 0.0000001, 0.01, 0.0001]
#        thickest_spillet_oil_distribution           :
#        distribution_of_thickest_spillet            :
#            min_time    : False
#            run_stats   : True
        
subsurface:
    concentration:
        bins: 200
        coefficient: 0.0001    
    gridded_products: {}
#        hit_count                                   :
#        hit_probability                             :
#        max_concentration                           :
#            cell_depth_range: [0.0, 50.0]
#        min_time                                    :


shore:
    thickness:
        bins: 200
        coefficient: 0.0001
    volume:
        bins: 200
        coefficient: 0.0001
    gridded_products: {}
#        shore_oil_stats                             :
#        hit_count                                   :
#        hit_probability                             :
#        min_time                                    :
#        oil_volume                                  :
#        oil_volume_distribution                     :
#        max_shore_grid_thickness                    :
#        distribution_of_max_shore_grid_thickness    :
#            min_time    : False
#            run_stats   : True        
        
        